version: '3.6'
services:
  app:
    #    image: openjdk:19-jdk
    env_file: ./docker/variables.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - DBUSER=${DBUSER}
        - DBPASSWORD=${DBPASSWORD}
        - DBHOST=${DBHOST}
    container_name: app
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "playerdb"
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
      - "./docker/db/initdb:/docker-entrypoint-initdb.d"
