version: '3.6'
services:
  app:
    env_file: ./docker/variables.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    ports:
      - 8080:8080
    tty: true


